oc_platform_homepage:
    path:    /
    defaults: { _controller: OCPlatformBundle:Default:index }

    
hello_the_world:
    path:    /hello-the-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

contact:
    path:    /contactez-nous
    defaults: { _controller: OCPlatformBundle:Advert:contact}